version: '3'
services:

  web:
    container_name: dansup_web
    image: takgyunim/dan-sup-web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: takgyunim/dan-sup-nginx
    ports:
      - 80:80
    depends_on:
      - web
