version: '3'
services:

  web:
    container_name: dansup-web
    image: dansup-web
    expose:
      - 8080
    ports:
      - 8080:8080
    tty: true

  nginx:
    container_name: dansup-nginx
    image: dansup-nginx
    ports:
      - 80:80
    depends_on:
      - dansup_web
    restart: always