version: '3'
services:

  web:
    container_name: web
    image: haensu/dansup-web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: haensu/dansup-nginx
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - 80:80
    depends_on:
      - dansup_web
    restart: always