version: '3'

services:

  web:
    container_name: dansup_web
    build:
      context: ./
      dockerfile: Dockerfile
    #    ports:
    #      - "8080:8080"
    expose:
      - 8080
    networks:
      - test_network

  nginx:
    container_name: nginx
    build: config/nginx
    ports:
      - "80:80"
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    depends_on:
      - web
    networks:
      - test_network

networks:
  test_network: