name: Deploy to EC2

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create Env File
        run: |
          touch .env
          echo "${{ secrets.ENV_VARS }}" >> .env

      - name: Make application-db.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.DATABASE }}" >> ./application-db.yml
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker Build and Push
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker build -t ${{ secrets.DOCKER_REPO }}/dansup-web .
          sudo docker push ${{ secrets.DOCKER_REPO }}/dansup-web
          sudo docker build -t ${{ secrets.DOCKER_REPO }}/dansup-nginx .
          sudo docker push ${{ secrets.DOCKER_REPO }}/dansup-nginx

      ## Docker Compose Up
      - name: Executing Remote Ssh Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p ~/srv/ubuntu
            cd /home/ubuntu/srv/ubuntu/
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/dansup-web
            sudo docker pull ${{ secrets.DOCKER_REPO }}/dansup-nginx
            sudo docker-compose up -d
            sudo docker image prune -f

